minimumReleaseAge: 4320 # 72 hours
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - "@phanect/lint@2026.8.29"
  - "@phanect/lint-astro@2026.8.29"

allowBuilds:
  esbuild: true
  unrs-resolver: true
