#:schema https://mise.jdx.dev/schema/mise.json

[tools]
node = { version = "24", corepack = true }
"npm:nushell" = "latest"

[hooks]
postinstall = "corepack enable"

[env]
_.file = "{{config_root}}/.env"

[settings]
jobs = 8
